// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth/auth.proto

/*
Package auth is a generated protocol buffer package.

It is generated from these files:
	auth/auth.proto

It has these top-level messages:
	LoginRequest
	LogoutRequest
	Jwt
*/
package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LogoutRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
}

func (m *LogoutRequest) Reset()                    { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string            { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()               {}
func (*LogoutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LogoutRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Jwt struct {
	Jwt string `protobuf:"bytes,1,opt,name=jwt" json:"jwt,omitempty"`
}

func (m *Jwt) Reset()                    { *m = Jwt{} }
func (m *Jwt) String() string            { return proto.CompactTextString(m) }
func (*Jwt) ProtoMessage()               {}
func (*Jwt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Jwt) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "auth.LoginRequest")
	proto.RegisterType((*LogoutRequest)(nil), "auth.LogoutRequest")
	proto.RegisterType((*Jwt)(nil), "auth.Jwt")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Auth service

type AuthClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Jwt, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type authClient struct {
	cc *grpc.ClientConn
}

func NewAuthClient(cc *grpc.ClientConn) AuthClient {
	return &authClient{cc}
}

func (c *authClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Jwt, error) {
	out := new(Jwt)
	err := grpc.Invoke(ctx, "/auth.Auth/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/auth.Auth/Logout", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthServer interface {
	Login(context.Context, *LoginRequest) (*Jwt, error)
	Logout(context.Context, *LogoutRequest) (*google_protobuf.Empty, error)
}

func RegisterAuthServer(s *grpc.Server, srv AuthServer) {
	s.RegisterService(&_Auth_serviceDesc, srv)
}

func _Auth_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Auth_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.Auth/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Auth_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.Auth",
	HandlerType: (*AuthServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Auth_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Auth_Logout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "auth/auth.proto",
}

func init() { proto.RegisterFile("auth/auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 254 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x4f, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0xa5, 0xb6, 0x06, 0x3b, 0x28, 0xea, 0x8a, 0xb5, 0xc4, 0x8b, 0xe4, 0xa0, 0x1e, 0x64, 0x03,
	0x8a, 0x3f, 0xa0, 0x15, 0x05, 0xa5, 0x07, 0xa9, 0xbf, 0x20, 0x4d, 0x67, 0x93, 0x95, 0x24, 0xb3,
	0xee, 0x87, 0xc1, 0x7f, 0x2f, 0x9b, 0x4d, 0xaa, 0x97, 0x61, 0xde, 0xbc, 0x99, 0x37, 0xef, 0xc1,
	0x71, 0xe6, 0x6c, 0x99, 0xfa, 0xc2, 0x95, 0x26, 0x4b, 0x6c, 0xe2, 0xfb, 0xf8, 0xb2, 0x20, 0x2a,
	0x2a, 0x4c, 0xbb, 0xd9, 0xc6, 0x89, 0x14, 0x6b, 0x65, 0x7f, 0xc2, 0x4a, 0xf2, 0x02, 0x87, 0x2b,
	0x2a, 0x64, 0xb3, 0xc6, 0x2f, 0x87, 0xc6, 0xb2, 0x18, 0x0e, 0x9c, 0x41, 0xdd, 0x64, 0x35, 0xce,
	0x47, 0x57, 0xa3, 0xdb, 0xe9, 0x7a, 0x87, 0x3d, 0xa7, 0x32, 0x63, 0x5a, 0xd2, 0xdb, 0xf9, 0x5e,
	0xe0, 0x06, 0x9c, 0xdc, 0xc0, 0xd1, 0x8a, 0x0a, 0x72, 0x76, 0x10, 0x9a, 0x41, 0xe4, 0x0f, 0x5f,
	0xb7, 0xbd, 0x4c, 0x8f, 0x92, 0x0b, 0x18, 0xbf, 0xb5, 0x96, 0x9d, 0xc0, 0xf8, 0xb3, 0xb5, 0x3d,
	0xe7, 0xdb, 0x7b, 0x84, 0xc9, 0xc2, 0xd9, 0x92, 0x5d, 0xc3, 0x7e, 0xe7, 0x88, 0x31, 0xde, 0x45,
	0xf9, 0x6f, 0x2f, 0x9e, 0x86, 0x99, 0x57, 0x78, 0x84, 0x28, 0x7c, 0x64, 0x67, 0xbb, 0xc5, 0xbf,
	0xff, 0xf1, 0x8c, 0x87, 0xd8, 0x7c, 0x88, 0xcd, 0x9f, 0x7d, 0xec, 0xe5, 0x1d, 0x9c, 0xe6, 0x54,
	0x73, 0x41, 0x24, 0x64, 0x85, 0xda, 0xf0, 0x5c, 0x94, 0xcb, 0xf3, 0x27, 0x51, 0x2e, 0x94, 0xaa,
	0x64, 0x9e, 0x59, 0x49, 0xcd, 0x07, 0xea, 0x6f, 0x99, 0xe3, 0xfb, 0x68, 0x13, 0x75, 0xd7, 0x0f,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x44, 0x3f, 0xe0, 0x0d, 0x5b, 0x01, 0x00, 0x00,
}
