package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// ApplicationConfig application config
// swagger:model ApplicationConfig
type ApplicationConfig struct {

	// application
	Application string `json:"application,omitempty"`

	// configuration
	Configuration ConfigurationEntries `json:"configuration,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this application config
func (m *ApplicationConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
