package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ApplicationVersion application version
// swagger:model ApplicationVersion
type ApplicationVersion struct {

	// default version
	DefaultVersion string `json:"defaultVersion,omitempty"`

	// versions
	Versions []string `json:"versions"`
}

// Validate validates this application version
func (m *ApplicationVersion) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVersions(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApplicationVersion) validateVersions(formats strfmt.Registry) error {

	if swag.IsZero(m.Versions) { // not required
		return nil
	}

	return nil
}
