package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// ConfigurationEntries configuration entries
// swagger:model ConfigurationEntries
type ConfigurationEntries interface{}
